#!/bin/bash

# checks if there exists upgrade to the version specified on the root project. Does not make any change.
# -ntp is to have No Transfer Progress ; -pl . means "project list : ."

reset
echo checking plugins on root module
echo
mvn -ntp versions:display-plugin-updates -pl .
echo
echo checking dependencies on root module
echo
mvn -ntp versions:display-dependency-updates -pl .
