name: Maven post-PR

on:
  pull_request:
    branches: 
      - master
    types: [closed]
 
jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    name: Java 17 post-process
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'
    - name: update versions
      run: mvn --batch-mode -ntp versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: clean test
      run: mvn --batch-mode -ntp clean install
    - name: push changes
      uses: stefanzweifel/git-auto-commit-action@v6
        